name: airflow-monitor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.0
  - pip:
    - fastapi==0.100.0
    - uvicorn==0.22.0
    - requests==2.31.0
    - python-dotenv==1.0.0
    - httpx==0.24.1 